id: I9D94BA84
legacy_id: P006821
ocr_import_info:
  bdrc_scan_id: W4CZ74375
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T11:21:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:04:18.111458+00:00'
last_modified: 2022-09-04 05:04:49.165883
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74375
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74375
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དེབ་ཐེར་སྔོན་པོ།
  author: འགོས་ལོ་ཙཱ་བ་གཞོན་ནུ་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.38743851659300016
  ocr_word_median_confidence_index: 0.3100000023841858
quality: null
bases:
  I4CZ74377:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74377
      total_pages: 972
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74377.txt
    statistics:
      ocr_word_median_confidence_index: 0.3100000023841858
      ocr_word_mean_confidence_index: 0.38743851659300016
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
